// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkHLY6fbm0BSSKXKJi_GHipL1xGsTeYKM',
    appId: '1:753991832489:web:12e354255b9e79fe296ab8',
    messagingSenderId: '753991832489',
    projectId: 'e-commerce-app-2e859',
    authDomain: 'e-commerce-app-2e859.firebaseapp.com',
    storageBucket: 'e-commerce-app-2e859.appspot.com',
    measurementId: 'G-DPYRY560QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbplYMYvdTk7RJUhdMuvXCYWEd3ln2SUs',
    appId: '1:753991832489:android:5d2d4529719bb247296ab8',
    messagingSenderId: '753991832489',
    projectId: 'e-commerce-app-2e859',
    storageBucket: 'e-commerce-app-2e859.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZQmnaanqftYX6AtO9bSra_BMIPvun9YA',
    appId: '1:753991832489:ios:ee7e90f8318cbc3d296ab8',
    messagingSenderId: '753991832489',
    projectId: 'e-commerce-app-2e859',
    storageBucket: 'e-commerce-app-2e859.appspot.com',
    iosClientId: '753991832489-2gdchs130hl5lkr5fts2m376lmvib2tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZQmnaanqftYX6AtO9bSra_BMIPvun9YA',
    appId: '1:753991832489:ios:ee7e90f8318cbc3d296ab8',
    messagingSenderId: '753991832489',
    projectId: 'e-commerce-app-2e859',
    storageBucket: 'e-commerce-app-2e859.appspot.com',
    iosClientId: '753991832489-2gdchs130hl5lkr5fts2m376lmvib2tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
